[alias]
tests = "test --all"
uitest = "test --test compile-test"
uibless = "test --test compile-test -- -- --bless"

[build]
# -Zbinary-dep-depinfo allows us to track which rlib files to use for compiling UI tests
rustflags = ["-Zunstable-options", "-Zbinary-dep-depinfo"]
target-dir = "target"

[unstable]
binary-dep-depinfo = true

[profile.dev]
split-debuginfo = "unpacked"

[env]
# RPL_PATS = "docs/patterns/CVE-2021-27376-MIR.rpl"
