[package]
name = "rpl_patterns"
version.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
edition.workspace = true

[dependencies]
rpl_macros.workspace = true
rpl_match.workspace = true
rpl_mir.workspace = true
rpl_context.workspace = true
rpl_predicates.workspace = true

[dev-dependencies]
libc.workspace = true
pin-project.workspace = true

[features]

[package.metadata.rust-analyzer]
# This crate uses #[feature(rustc_private)]
rustc_private = true
