name: Rust CI

on:
  push:
    branches: [ dev ]
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CONTRIBUTING.md'
      - '.vscode/**'
  pull_request:
    branches: [ master, pest ]
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CONTRIBUTING.md'
      - '.vscode/**'

jobs:
  build:
    name: Cargo Test, Clippy and Format
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: cargo fmt --check
      - run: cargo test --all
        if: github.ref_name != 'pest' && github.base_ref != 'pest'
      # Exclude ui tests for pest branch
      - run: cargo test --all --exclude rpl
        if: github.ref_name == 'pest' || github.base_ref == 'pest'
      - run: cargo clippy -- -D warnings
      - run: cargo install --path .
      - run: cargo rpl --workspace --all-targets
        if: github.ref_name != 'pest' && github.base_ref != 'pest'
      # - uses: actions-rust-lang/audit@v1.2.4
